### ISSUE TITLE
Any value passed test in main.e2e.js

### ISSUE THREAD

**Issue by jkalandarov** [automationbro/webdriverio-v7#1]
I've been copying your code while watching your youtube tutorial. The test passed no matter what value I put to test.
Then I copied your code from main.e2e.js and wdio.config.js and pasted it to my own files. `expect(listExamples).toBeElementsArrayOfSize({gte: 100});` this condition passed the test.

Any idea what I am doing wrong?

Thanks in advance

**Comment by dilpreetj** [comment]
YouTube videos are using v6 so it won't work if you are using v7. You can checkout this course to learn how to work with v7 Webdriverio - https://www.udemy.com/course/webdriverio-complete-beginner-course/?referralCode=5190D58FC784B9F4E1AD

In your case, the reason its passing is because its using `async` mode so you need to handle the promises when setting up assertions.
